export {default as Header} from './Header'
export {default as Hero} from './Hero'
export {default as Slider} from './Slider'
export {default as Virtual} from './Virtual'
export {default as Products} from './Products'
export {default as Testimonial} from './Testimonial'
export {default as Footer} from './Footer'
