export {default as Header} from './Header/Header'
export {default as Hero} from './Hero/Hero'
export {default as Slider} from './Slider/Sider'
export {default as Virtual} from './Virtual/Virtual'
export {default as Products} from './Products/Products'
export {default as Testimonial} from './Testimonial/Testimonial'
export {default as Footer} from './Footer/Footer'
